version: '3.8'
services:
  db:
    image: postgres:18.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
      ports:
        -"5432:5432"
      volumes:
        -pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:9.8.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    depends_on:
      - db


  api:
    build: .
    command: uvicorn app:app --host 0.0.0.0 -- port 8000
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  pgdata: